mutation CreateSandboxUser($input: CreateSandboxUserInput!) {
  createSandboxUser(input: $input) {
    ... on Rejection {
      message
    }
    ... on CreateSandboxUserSuccessPayload {
      sandboxUser {
        id
      }
    }
  }
}
