mutation CreateSandboxUser($firstName: String!, $lastName: String!) {
  createSandboxUser(
    input: {
      autoConsent: true
      birthDate: "1970-01-01"
      firstName: $firstName
      lastName: $lastName
      nationalityCCA3: "FRA"
    }
  ) {
    ... on CreateSandboxUserSuccessPayload {
      sandboxUser {
        id
      }
    }
  }
}

mutation CreateSandboxIdentification($userId: String!) {
  createSandboxIdentification(
    input: { userId: $userId, process: PVID, levels: { expert: Valid, pvid: Valid } }
  ) {
    ... on CreateSandboxIdentificationSuccessPayload {
      sandboxIdentification {
        id
      }
    }
  }
}

mutation EndorseSandboxUser($id: String!) {
  endorseSandboxUser(input: { id: $id }) {
    ... on EndorseSandboxUserSuccessPayload {
      sandboxUser {
        id
      }
    }
  }
}

mutation UpdateAccountHolder($input: UpdateAccountHolderInput!) {
  updateAccountHolder(input: $input) {
    __typename
  }
}
