FROM 326954429656.dkr.ecr.eu-west-1.amazonaws.com/golden-images/node:24.21.0-trixie-slim-swan.1 AS builder
WORKDIR /app
ADD ./server/ ./
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN npm install -g pnpm@latest-10
RUN pnpm install --no-frozen-lockfile

FROM 326954429656.dkr.ecr.eu-west-1.amazonaws.com/golden-images/node:24.21.0-trixie-slim-swan.1
WORKDIR /app
COPY --chown=node:node --from=builder /app ./
CMD ["npm", "run", "start-swan"]
EXPOSE 8080
