// This file was automatically generated by the tggl CLI

import "tggl-client";

declare module "tggl-client" {
  export interface TgglContext {
    accountCountry: "BEL" | "DEU" | "ESP" | "FRA" | "ITA" | "NLD";
    accountId: string;
    capitalDepositCaseId: string;
    cardToken: string;
    carrierCountryCCA3: string;
    carrierCountryIsoCode: string;
    carrierName: string;
    carrierNetworkIdentifier: string;
    carriersCountryCode: string;
    countryCode: string;
    doesUserHaveAProject: boolean;
    email: string;
    environment: "development" | "master" | "preprod" | "prod";
    environmentType: "admin" | "live" | "sandbox";
    existingUser: boolean;
    iban: string;
    ip?: string;
    ipAddressCountry: string;
    ipAndPhoneCountryMismatch: boolean;
    label: string;
    merchantId: string;
    oAuthClientId: string;
    phoneCountryCode: string;
    phoneNumber: string;
    projectId: string;
    reference: string;
    referer?: string;
    serviceDomain: string;
    serviceName: string;
    smsOtpInitiator: string;
    timestamp: string | number;
    transactionId: string;
    userId: string;
  }

  export interface TgglFlags {
    account_contract_send_tcu_notifications: null | true;
    account_contract_use_swan_tcu_templates_for_disabled_projects: true;
    account_contract_use_swan_templates_for_tcu_notifications: true;
    accountContractActivateRPCAgent: boolean;
    accountContractFetchAccountMembershipsByUserDataLoaded: boolean;
    accountContractPartnersCanOpenAdditionalAccounts: boolean;
    activate_card_package_on_card_product: boolean;
    activate_digital_card_use_case: boolean;
    activate_satd_manual_seizure_in_payment: boolean;
    activatePhysicalCardNotificationEnabledGlobally: boolean;
    add_default_expiration_for_suvc_one_of_at_creation: boolean;
    adminAuthThroughBFF: boolean;
    allowNoCodeOnboardingV1: boolean;
    allowServerToServerConsent: boolean;
    arbirtray: 1 | 2;
    aria_enabled: boolean;
    aria_redirect_to_swan_project: boolean;
    asset_freeze_approve_list_enabled: true;
    back_office_bank_verlag_event_generation_improvements: true;
    bailiff_account_matching_mode:
      | "AccountContractAndPayment"
      | "AccountContractOnly"
      | "PaymentOnly";
    bankingBulkTransfer: true;
    beneficiaries: true;
    billing_card_package_types_configuration_enabled: boolean;
    billing_check_return_enabled: boolean;
    billing_kafka_consumers_enabled: boolean;
    billing_sms_notification: boolean;
    billing_tap_to_pay_configuration_enabled: boolean;
    billing_usage_event_enabled: boolean;
    block_reupload_register_extract: boolean;
    blockOtpRequestIfAntibotTokenIsInvalid: true;
    "bnp-mock-mode-sct-instant":
      | "ACCP"
      | "HTTP-500"
      | "HTTP-503"
      | "PDNG"
      | "RJCT-AC04"
      | "RJCT-AM04"
      | "RJCT-AM05"
      | "RJCT-FF01";
    can_manage_beneficiary_for_untrusted_beneficiary: boolean;
    canHandleBulkPayment: boolean;
    card_out_partner_control_blocked_merchant_ids:
      | "2000000014,2250820,526567000264379,526567000264304"
      | '""';
    cardExpirationNotificationEnabledGlobally: boolean;
    cardInsufficientFundsNotificationEnabledGlobally: boolean;
    cardInsuranceActivation: boolean;
    cardInsuranceProjectCreation: boolean;
    cardInvalidExpirationDateNotificationEnabledGlobally: boolean;
    cardPackage: boolean;
    cardPermanentlyBlockedNotificationEnabledGlobally: boolean;
    cardPinInvalidNotificationEnabledGlobally: boolean;
    cardSpendingLimitReachedNotificationEnabledGlobally: boolean;
    categoryPurposeOnSCTOutInitiation: boolean;
    check_order_of_xpay_events: boolean;
    ciao_es_enabled: boolean;
    cms_call_cema_carte_for_choose_pin: true;
    cms_choose_pin_token_always_valid: true;
    create_verification_renewal_cron: boolean;
    createFraudPreventionCampaign: boolean;
    createVerificationRenewalFlowChart: boolean;
    createVerificationRenewalInWaitingForInformationStatus: boolean;
    dashboardAccountClosingLink: true;
    dashboardBanner: null | {
      text: "Due to exceptionally high volumes for KYC reviews and support tickets, response times will be longer than normal. Thank you for your patience.";
      title: "KYC & Support";
    };
    dashboardInsightsServiceSection: boolean;
    dashboardNotificationSettings: true;
    dashboardProjectMemberToken: true;
    dataExportAccount: boolean;
    dataExportAccountHolder: boolean;
    dataExportAccountMembership: boolean;
    dataExportCard: boolean;
    dataExportOnboarding: boolean;
    dataExportTransactions: boolean;
    dataExportUser: boolean;
    deferredDebitCard: boolean;
    disable_emails_for_capital_deposit_case: boolean;
    disable_expert_identification_level: true;
    disable_pvid_identification_level: true;
    disable_qes_identification_level: true;
    disableWebBanking: boolean;
    displaySsoButton: boolean;
    documentMigrationRead: boolean;
    documentMigrationWrite: boolean;
    dont_change_default_expiration_for_suvc_one_off_at_update: boolean;
    emi_banking_rpc_agent: boolean;
    emi_tax_rpc_agent: boolean;
    "emi-banking-bnp-balance-computation-strategy": boolean;
    emiBankingActivateRPCAgent: boolean;
    enable_automatic_identity_documents_upload: boolean;
    enable_available_balance_request_sardine: boolean;
    enable_card_link_risk_assessment: boolean;
    enable_card_risk_assessment: boolean;
    enable_card_risk_backfill: boolean;
    enable_credit_zero_amount_author_public_api: boolean;
    enable_document_convertor_from_csv_generation: boolean;
    enable_document_convertor_generation: boolean;
    enable_document_generation_by_document_convertor: boolean;
    enable_immediate_release_on_fuel_dispenser_capture: boolean;
    enable_mastercard_presettlement: true;
    enable_mastercard_presettlement_reconciliation: true;
    enable_new_account_statement_file_name: boolean;
    enable_optimized_monthly_statement_generation: boolean;
    enable_transaction_enrichment_from_origin_transaction: boolean;
    enable_transaction_risk_backfill: boolean;
    enableBouyguesFraudPreventionPage: boolean;
    enableEmailConfirmationAtProjectCreation: boolean;
    enableFraudPreventionPage: boolean;
    enableIdentityTheftPreventionPage: true;
    end_customer_billing_enabled: boolean;
    end_customer_ict_billing_enabled: boolean;
    fctInRejectOnLimitedAccountsEnabled: boolean;
    FeatureFlagCreditEnabled: 1 | 2;
    fetchSeonSignalsForAccountMembership: boolean;
    forceAllowDesktopAuth: boolean;
    free_units_enabled: boolean;
    frontDesktopToMobileIdentification: boolean;
    frontendProjectConfirmation: boolean;
    generate_mastercard_emi_banking: true;
    handle_third_party_events: boolean;
    ict_validation_rejection_enabled: boolean;
    identificationUserInfoCollectionAndReview: boolean;
    identityBirthDataCollection: true;
    incomingForeignTransferScreeningEnabled: true;
    incomingForeignTransferScreeningLimit: 50;
    incomingTransferInstScreeningEnabled: boolean;
    incomingTransferScreeningDualRunEnabled: boolean;
    incomingTransferScreeningEnabled: boolean;
    incomingTransferScreeningLimit: 50;
    initiate_international_credit_transfer_outgoing: boolean;
    inPersonCardPaymentMethodEnabled: boolean;
    is_onboarding_v2_enabled_for_capital_deposit: boolean;
    is_onboarding_v2_enabled_for_iam: boolean;
    isAccountAdminChangeEnabled: boolean;
    isConsentFailedEventEnabled: true;
    isCustomerPasswordResetAvailable: true;
    isDashboardSignupForNewSuspiciousUserCheckEnabled: boolean;
    isForceDesktopAuthenticationEnabled: boolean;
    isFrenchIndividualFlowAutomationEnabled: boolean;
    isPhoneNumberSuspicious: boolean;
    isScaDelegationEnabled: boolean;
    isTaxUserInformationInRecommendedIdentificationFlowEnabled: boolean;
    isThreeDsPaymentAllowToBeQueried: boolean;
    "kafka-consumers-enabled": boolean;
    kycAccountHoldersVerificationsView: true;
    kycActivateRPCAgent: boolean;
    la_poste_tracked_international_active: boolean;
    lago_partner_event_use_billing_periods: boolean;
    lockRecomputeEnableB2B: true;
    "mcd-process-auto-retry": boolean;
    merchantWebBanking: boolean;
    newGqlGateway: boolean;
    OnboardingV2NoCode: boolean;
    OTPLinkForIdentifications: boolean;
    outboundFundsTransferRejectedNotificationEnabledGlobally: boolean;
    outboundFundsTransferSuccessfulNotificationEnabledGlobally: boolean;
    packageSpendingLimit: { Essential: 40000 | 60000; Premium: 100000; Standard: 10000 | 30000 };
    partner_billing_v1_5_enabled: boolean;
    passcodeResetEmailVerification: boolean;
    passcodeResetFaceAuthVerification: boolean;
    passcodeResetIdentificationVerification: boolean;
    passcodeResetNoVerification: boolean;
    paymentSpendingAcprLimitedAccountsLevel: "NO_SPENDING" | "SPENDING_READONLY" | "SPENDING_USE";
    pennylane_specific_spending_limits_on_card_package: boolean;
    pexTcuEventKillSwitch: boolean;
    processSardineWebhookAlerts: boolean;
    ProcessTopographWebhooks: boolean;
    recurring_suvc_fee_enabled: boolean;
    refundFeesActivateFixOnInvertedAccountIds: boolean;
    reKYCRequestIdentityProof: boolean;
    return_ict_in_enabled: boolean;
    return_transaction_mutation_ict_in: boolean;
    riskScoringStrategy:
      | "double_run_in_house"
      | "double_run_marble"
      | "double_run_relevant"
      | "in_house_only"
      | "marble_only";
    satd_account_matching_check_for_risk_suspicion: boolean;
    scaAnonymizeUserInfo: boolean;
    scaIAMDailyMaximumNumberOfSignInPerIp: 10 | 100 | 1000 | 100000 | 20 | 3 | 5;
    scaIAMDailyMaximumNumberOfSignInPerPhoneNumber: 10 | 100 | 1000 | 100000 | 5;
    scaIsCountrySuspiciousCheckEnabled: boolean;
    scaIsInternalOtpEnabled: boolean;
    scaIsLoginChallengeCheckEnabled: boolean;
    scaIsNotificationManagerEnabled: boolean;
    scaIsPhoneCountryCodeBlocked: boolean;
    scaIsSingleDeviceAuthEnabled: boolean;
    scaIsWebBankingBrandlessLoginChallengeCheckEnabled: boolean;
    scale_merchant_onboarding_bo: boolean;
    scaleMerchantOnboarding: boolean;
    scaShouldIncludeCustomSubdomainInConsentUrl: boolean;
    scaShouldPassSessionIdToConsentable: boolean;
    scaSsoPostLogoutRedirectUrl: "authorize" | "dashboard" | "login" | "prelogin";
    scaV1ToV2IdsConversionBatchSize: 0 | 10 | 100 | 20 | 200 | 3 | 5 | 50 | 75;
    scoreThresholdHCaptcha: 0.75 | 0.8 | 0.9 | 1.5;
    scoring_mode_fct_in: "risk_assessment" | "scoring_and_risk_assessment_dry_run" | "scoring_only";
    scoring_mode_fct_out:
      | "risk_assessment"
      | "scoring_and_risk_assessment_dry_run"
      | "scoring_only";
    scoring_mode_sct_in: "risk_assessment" | "scoring_and_risk_assessment_dry_run" | "scoring_only";
    scoring_mode_sct_out:
      | "risk_assessment"
      | "scoring_and_risk_assessment_dry_run"
      | "scoring_only";
    sctInstEnabled: boolean;
    send_account_invoice_generated_event: boolean;
    send_activate_physical_card_notification: boolean;
    send_otp_from_xpay_reporting_pwm_token: boolean;
    sendBusinessAndCustomerDataToSardine: boolean;
    sendCreditAndZeroAmountAuthorization: boolean;
    sendValidationInsteadOfForbiddenRejection: boolean;
    sendVerificationRenewalEmails: boolean;
    sendVerificationRenewalEmailsWhenOverdue: boolean;
    sepaDirectDebitInV2: true;
    SepaDirectDebitV2ActivationFlag: true;
    setIssuingProcessorCardProductOnRenewFeature: boolean;
    setUpAdminRole: boolean;
    shareholderMigrationRead: boolean;
    shareholderMigrationWrite: boolean;
    should_use_new_closing_reasons: boolean;
    shouldHistorizeIncomingVOPRequest: boolean;
    shouldIncludeAllAccountStatusesForMultiAccountLimit: boolean;
    shouldRestrictMultiAccountCreationWhenSuspensionExists: boolean;
    storeMonextAuthenticationRequest: boolean;
    supportingDocumentsUseBucketV2: boolean;
    suspend_digital_card_on_cancel_physical_card_saga_enabled: boolean;
    suspend_resume_digital_cards_on_account_suspension_ipc: boolean;
    swan_generate_missing_bank_details: true;
    swan_supports_local_belgian_iban: boolean;
    swan_supports_local_belgian_iban_dashboard: boolean;
    swan_supports_local_italian_iban_dashboard: true;
    swan8n_ignore_account_events: boolean;
    swan8n_ignore_account_holder_events: boolean;
    swan8n_ignore_comply_advantage_webhooks: boolean;
    swan8n_ignore_external_account_events: boolean;
    swan8n_ignore_funding_limit_settings_events: boolean;
    swan8n_ignore_onboarding_events: boolean;
    swan8n_ignore_supporting_document_collection_events: boolean;
    swan8n_ignore_supporting_document_events: boolean;
    swan8n_ignore_workflows_events: boolean;
    tapToPay: boolean;
    testABTesting: "A" | "B";
    testE: "A" | "B";
    transactionVerification: boolean;
    transfer_suvc_to_legal_rep_on_closed_account_membership: boolean;
    trusted_beneficiary_transfers_consent_free_enabled: boolean;
    twilioRatio: 0 | 0.2 | 0.5 | 0.6 | 0.8 | 0.95 | 1;
    updateBusinessAndCustomerDataToSardine: boolean;
    use_mailjet_subaccount_for_mass_emailing: true;
    use_notification_manager: boolean;
    "use-outbox-pattern": boolean;
    useNotificationStackToSendNewMembershipEmail: boolean;
    useNotificationStackToSendTCUUpdates: boolean;
    useOutboxTableForBankDetailsGeneration: boolean;
    usePaymentV2FlowForAccountFunding: boolean;
    useTwilioVerifyServiceSidAlan: true;
    validation_of_postal_code: boolean;
    webhookInitializeExpireOldEventLogsCron: boolean;
    webhookInitializeUpdateConsumerCron: boolean;
    webhookRunExpireOldEventLogsCron: boolean;
    webhookRunUpdateConsumerCron: boolean;
    webhookSendWebhookTokenHeader: boolean;
    webhookSubscriptionLimit: boolean;
    xpay_provisioning_eligibility_v2_enabled: boolean;
    xpay_provisioning_high_risk_yellow_without_idv_enabled: boolean;
  }
}
