// This file was automatically generated by the tggl CLI

import "tggl-client";

declare module "tggl-client" {
  export interface TgglContext {
    userId: string;
    email: string;
    timestamp: string | number;
    referer?: string;
    ip?: string;
    projectId: string;
    accountCountry: "FRA" | "NLD" | "DEU" | "ESP";
    environment: "master" | "preprod" | "prod" | "development";
    environmentType: "sandbox" | "live" | "admin";
    serviceName: string;
  }

  export interface TgglFlags {
    add_new_reason_codes_for_capital_deposit_documents: true;
    merchantPaymentMethodRequestUpdate: true;
    account_contract_enable_nl_white_label_tcu_template: true;
    account_contract_use_swan_tcu_templates_for_disabled_projects: true;
    teamManagementV2: true;
    sepaGatewayPublishSctInstEventsThroughFastKafkaTopics: true;
    account_contract_choose_pin_code_enabled: true;
    isPusherFixed: true;
    frontendActivateMerchantProfileInWebBanking: true;
    requestCardPaymentMethod: true;
    KYCUseInternalSystemToCollectSupportingDocuments: true;
    use_mailjet_subaccount_for_mass_emailing: true;
    bankingBulkTransfer: true;
    shouldUseICTV2: true;
    paymentLink: true;
    account_contract_use_swan_templates_for_tcu_notifications: true;
    kycAccountHoldersVerificationsView: true;
    end_customer_usage_payment_v2_enabled: boolean;
    twilioRatio: 0.8 | 1 | 0.5 | 0;
    kycUseKycServiceForCompanyWorkflow: boolean;
    end_customer_ict_billing_enabled: boolean;
    testScalaFeatureFlag: "ASBABSBSDBAA";
    kyc_request_first_transfer: boolean;
    account_contract_send_tcu_notifications: true | null;
    lago_signature_verification_enabled: boolean;
    use_optimized_count_in_paginate: boolean;
    ciao_es_enabled: boolean;
    setIssuingProcessorCardProductOnRenewFeature: boolean;
    renewPhysicalCardFeature: boolean;
    end_customer_billing_enabled: boolean;
    virtual_card_subscription_enabled: boolean;
    isCheckRedirectVerificationCodeCalled: boolean;
    account_subscription_enabled: boolean;
    toRenewPhysicalCardFeatureEnabled: boolean;
    billing_v2_enabled: boolean;
    card_management_system_schedules_enabled: boolean;
    synchronize_fee_settings_enabled: boolean;
    card_management_system_outboxer_enabled: boolean;
    testFrontEnd: boolean;
    isNotificationsServiceEnabled: boolean;
    notificationServiceUsageRatio: 0.8 | 1 | 0.5 | 0 | 0.2;
    renewVirtualCardFeature: boolean;
    complianceReason_default_account_closing: boolean;
    addInternationalBeneficiary: boolean;
    kycUseKycServiceForFintectureWorkflow: boolean;
    n8n_screening_use_account_contract: boolean;
    enableSandboxMutations: boolean;
    lago_end_customer_enabled: boolean;
    initiate_international_credit_transfer_outgoing: boolean;
    account_contract_monext_openapi_enabled: boolean;
    create_capital_deposit_case_input_validation_enabled: boolean;
    account_membership_subscription_enabled: boolean;
    account_contract_card_services_activated: boolean;
    kyc_create_kyc_case: boolean;
    addSepaBeneficiary: boolean;
    account_contract_card_jobs_activated: boolean;
    new_physical_card_model_enabled: boolean;
    cancelPhysicalCardAtExpirationFeature: boolean;
    closure_subscription_enabled: boolean;
    swan_supports_local_italian_iban: true;
    mutationAddInternationalTrustedBeneficiary: boolean;
    sandboxIdentification: boolean;
  }
}
