// This file was automatically generated by the tggl CLI

import 'tggl-client'

declare module 'tggl-client' {
  export interface TgglContext {
    userId: string
    email: string
    timestamp: string | number
    referer?: string
    ip?: string
    countryCode: number
    projectId: string
    accountCountry: "FRA" | "NLD" | "DEU" | "ESP" | "ITA"
    environment: "master" | "preprod" | "prod" | "development"
    environmentType: "sandbox" | "live" | "admin"
    serviceName: string
  }

  export interface TgglFlags {
    incomingTransferInstScreeningEnabled: true
    bankingBulkTransfer: true
    sepaGatewayPublishSctInstEventsThroughFastKafkaTopics: true
    swan_account_membership_migration: true
    frontendActivateMerchantProfileInWebBanking: true
    merchantPaymentMethodRequestUpdate: true
    KYCUseInternalSystemToCollectSupportingDocuments: true
    account_contract_choose_pin_code_enabled: true
    teamManagementV2: true
    shouldUseICTV2: true
    requestCardPaymentMethod: true
    account_contract_use_swan_templates_for_tcu_notifications: true
    kycAccountHoldersVerificationsView: true
    use_mailjet_subaccount_for_mass_emailing: true
    paymentLink: true
    choosePINCode: true
    isPusherFixed: true
    beneficiaries: true
    incomingForeignTransferScreeningEnabled: true
    merchantWebBanking: true
    account_contract_use_swan_tcu_templates_for_disabled_projects: true
    isScaDelegationEnabled: boolean
    enableSandboxMutations: boolean
    sandboxIdentification: boolean
    toRenewPhysicalCardFeatureEnabled: boolean
    mutationAddSepaTrustedBeneficiary: boolean
    testFrontEnd: boolean
    new_physical_card_model_enabled: boolean
    ciao_es_enabled: boolean
    setIssuingProcessorCardProductOnRenewFeature: boolean
    end_customer_billing_enabled: boolean
    billing_v2_enabled: boolean
    renewVirtualCardFeature: boolean
    addInternationalBeneficiary: boolean
    cancelPhysicalCardAtExpirationFeature: boolean
    closure_subscription_enabled: boolean
    renewPhysicalCardFeature: boolean
    account_contract_enable_maestro_provider: boolean
    use_enriched_transaction_data: boolean
    use_optimized_count_in_paginate: boolean
    international_credit_transfer_outgoing_remittance_settlement_enabled: boolean
    account_contract_enable_maestro_provider_in_print_physical_card: boolean
    billing_v2_account_invoice_updated_event_enabled: boolean
    return_transaction_mutation: boolean
    isCheckRedirectVerificationCodeCalled: boolean
    notificationServiceUsageRatio: 0.8 | 1 | 0.5 | 0 | 0.2
    card_management_system_schedules_enabled: boolean
    card_management_system_outboxer_enabled: boolean
    lago_end_customer_enabled: boolean
    account_contract_monext_openapi_enabled: boolean
    isNotificationsServiceEnabled: boolean
    incomingTransferScreeningEnabled: boolean
    account_contract_card_services_activated: boolean
    addSepaBeneficiary: boolean
    account_contract_card_jobs_activated: boolean
    swan_supports_local_italian_iban: true
    mutationAddInternationalTrustedBeneficiary: boolean
    card_management_system_create_default_card_product_when_new_project: boolean
    end_customer_usage_payment_v2_enabled: boolean
    kycUseKycServiceForCompanyWorkflow: boolean
    card_management_system_activate_finalize_saga_use_case: boolean
    end_customer_ict_billing_enabled: boolean
    testScalaFeatureFlag: "ASBABSBSDBAA"
    account_contract_send_tcu_notifications: true | null
    initiate_international_credit_transfer_outgoing: boolean
    kycUseKycServiceForFintectureWorkflow: boolean
    useInternationalBeneficiary: boolean
    isCallToFeatureFlagProviderInBackground: boolean
    incomingForeignTransferScreeningLimit: 50
    switch_simulate_to_invoice_v2: boolean
    international_credit_transfer_swift_markup_enabled: boolean
    incomingTransferScreeningLimit: 50
    name_matching_use_valid_names_enabled: boolean
    paymentLedgerCommunicationMode: "kafka" | "kafka_shadow_nats" | "nats_fallback_kafka" | "nats"
    twilioRatio: 0.8 | 1 | 0.5 | 0 | 0.95 | 0.6
    use_swan_public_data_s3: boolean
    isPhoneNumberCountryCodeBlocked: boolean
  }
}