// This file was automatically generated by the tggl CLI

import 'tggl-client'

declare module 'tggl-client' {
  export interface TgglContext {
    userId: string
    email: string
    timestamp: string | number
    referer?: string
    ip?: string
    projectId: string
    accountCountry: "FRA" | "NLD" | "DEU" | "ESP" | "ITA"
    environment: "master" | "preprod" | "prod" | "development"
    environmentType: "sandbox" | "live" | "admin"
    serviceName: string
    countryCode: string
    cardToken: string
    iban: string
    capitalDepositCaseId: string
  }

  export interface TgglFlags {
    merchantDashboard: true
    enableIdentityTheftPreventionPage: true
    SepaDirectDebitV2ActivationFlag: true
    notificationManagerCardPaymentRefusedNotification: true
    use_fourthine_workflow_api: true
    asset_freeze_approve_list_enabled: true
    checks: true
    webhookSubscriptionLimit: true
    cms_call_cema_carte_for_choose_pin: true
    swan_account_membership_migration: true
    back_office_bank_verlag_event_generation_improvements: true
    use_mailjet_subaccount_for_mass_emailing: true
    sepaDirectDebitInV2: true
    merchantWebBanking: true
    sepaGatewayPublishSctInstEventsThroughFastKafkaTopics: true
    international_gateway_nats_consumer_enabled: true
    frontendActivateMerchantProfileInWebBanking: true
    teamManagementV2: true
    isPusherFixed: true
    account_contract_use_swan_tcu_templates_for_disabled_projects: true
    paymentLink: true
    bankingBulkTransfer: true
    requestCardPaymentMethod: true
    beneficiaries: true
    KYCUseInternalSystemToCollectSupportingDocuments: true
    merchantPaymentMethodRequestUpdate: true
    account_contract_choose_pin_code_enabled: true
    kycUseNewAmlLevelThreshold: true
    account_contract_use_swan_templates_for_tcu_notifications: true
    kycAccountHoldersVerificationsView: true
    deactivateUser: true
    KYCAllowGraphQLRequests: true
    swan_generate_missing_bank_details: true
    activateCardPaymentMethod: true
    useTwilioVerifyServiceSidAlan: true
    incomingForeignTransferScreeningEnabled: true
    card_management_system_activate_jobs_with_monext_call: boolean
    sandboxIdentification: boolean
    mutationAddSepaTrustedBeneficiary: boolean
    testFrontEnd: boolean
    new_physical_card_model_enabled: boolean
    dataExportTransactions: boolean
    ciao_es_enabled: boolean
    setIssuingProcessorCardProductOnRenewFeature: boolean
    incomingTransferInstScreeningEnabled: boolean
    end_customer_billing_enabled: boolean
    billing_v2_enabled: boolean
    addInternationalBeneficiary: boolean
    closure_subscription_enabled: boolean
    use_enriched_transaction_data: boolean
    use_optimized_count_in_paginate: boolean
    international_credit_transfer_outgoing_remittance_settlement_enabled: boolean
    return_transaction_mutation: boolean
    account_contract_enable_maestro_provider_in_print_physical_card: boolean
    billing_v2_account_invoice_updated_event_enabled: boolean
    isScaDelegationEnabled: boolean
    account_contract_enable_maestro_provider: boolean
    notificationServiceUsageRatio: 0.8 | 1 | 0.5 | 0 | 0.2
    card_management_system_outboxer_enabled: boolean
    card_management_system_schedules_enabled: boolean
    lago_end_customer_enabled: boolean
    account_contract_monext_openapi_enabled: boolean
    incomingTransferScreeningEnabled: boolean
    account_contract_card_jobs_activated: boolean
    account_contract_card_services_activated: boolean
    isNotificationsServiceEnabled: boolean
    handle_triple_webhook: boolean
    swan_supports_local_italian_iban: true
    mutationAddInternationalTrustedBeneficiary: boolean
    card_management_system_create_default_card_product_when_new_project: boolean
    end_customer_usage_payment_v2_enabled: boolean
    kycUseKycServiceForCompanyWorkflow: boolean
    end_customer_ict_billing_enabled: boolean
    testScalaFeatureFlag: "ASBABSBSDBAA"
    account_contract_send_tcu_notifications: true | null
    initiate_international_credit_transfer_outgoing: boolean
    useInternationalBeneficiary: boolean
    return_ict_in_enabled: boolean
    disable_emails_for_capital_deposit_case: boolean
    complete_capital_deposit_case_enabled: boolean
    incomingForeignTransferScreeningLimit: 50
    switch_simulate_to_invoice_v2: boolean
    international_credit_transfer_swift_markup_enabled: boolean
    name_matching_use_valid_names_enabled: boolean
    twilioRatio: 0.8 | 1 | 0.5 | 0 | 0.95 | 0.6
    incomingTransferScreeningLimit: 50
    dataExportUser: boolean
    monextNewRejectionCodeActivation: boolean
    enable_document_generation_by_document_convertor: boolean
    incomingTransferScreeningDualRunEnabled: boolean
    send_transaction_enriched_webhook: boolean
    enable_transaction_statements: boolean
    isPhoneNumberCountryCodeBlocked: boolean
    card_management_system_cance_cards_on_account_closed: boolean
    dataExportCards: boolean
    dataExportAccount: boolean
    dataExportAccountHolder: boolean
    dataExportOnboarding: boolean
    screeningSctInAndFctInWithNats: boolean
    card_management_system_activate_finalize_saga_use_case: boolean
    processed_identification_requires_valid_redirect_verification_status: boolean
    addSepaBeneficiary: boolean
  }
}