// This file was automatically generated by the tggl CLI

import "react-tggl-client";

declare module "react-tggl-client" {
  export interface TgglContext {
    accountCountry: "BEL" | "DEU" | "ESP" | "FRA" | "ITA" | "NLD";
    capitalDepositCaseId: string;
    cardToken: string;
    carrierCountryCCA3: string;
    carrierCountryIsoCode: string;
    carrierName: string;
    carrierNetworkIdentifier: string;
    carriersCountryCode: string;
    countryCode: string;
    doesUserHaveAProject: boolean;
    email: string;
    environment: "development" | "master" | "preprod" | "prod";
    environmentType: "admin" | "live" | "sandbox";
    iban: string;
    ip?: string;
    ipAddressCountry: string;
    ipAndPhoneCountryMismatch: boolean;
    label: string;
    phoneCountryCode: string;
    phoneNumber: string;
    projectId: string;
    reference: string;
    referer?: string;
    serviceName: string;
    smsOtpInitiator: string;
    timestamp: string | number;
    userId: string;
  }

  export interface TgglFlags {
    account_contract_send_tcu_notifications: null | true;
    account_contract_use_swan_tcu_templates_for_disabled_projects: true;
    account_contract_use_swan_templates_for_tcu_notifications: true;
    accountContractActivateRPCAgent: boolean;
    accountContractFetchAccountMembershipsByUserDataLoaded: boolean;
    accountContractPartnersCanOpenAdditionalAccounts: boolean;
    activate_calendar_spending_limits: boolean;
    activate_card_package_on_card_product: boolean;
    activate_digital_card_use_case: boolean;
    activate_satd_manual_seizure_in_payment: boolean;
    activatePhysicalCardNotificationEnabledGlobally: boolean;
    add_default_expiration_for_suvc_one_of_at_creation: boolean;
    adminAuthThroughBFF: boolean;
    allowServerToServerConsent: boolean;
    arbirtray: 1 | 2;
    aria_enabled: boolean;
    aria_redirect_to_swan_project: boolean;
    asset_freeze_approve_list_enabled: true;
    automaticallyMergeThirdParties: boolean;
    back_office_bank_verlag_event_generation_improvements: true;
    bailiff_account_matching_mode:
      | "AccountContractAndPayment"
      | "AccountContractOnly"
      | "PaymentOnly";
    bankingBulkTransfer: true;
    beneficiaries: true;
    billing_card_package_types_configuration_enabled: boolean;
    billing_check_return_enabled: boolean;
    billing_kafka_consumers_enabled: boolean;
    billing_sms_notification: boolean;
    block_reupload_register_extract: boolean;
    blockOtpRequestIfAntibotTokenIsInvalid: true;
    can_manage_beneficiary_for_untrusted_beneficiary: boolean;
    canHandleBulkPayment: boolean;
    cardExpirationNotificationEnabledGlobally: boolean;
    cardInsufficientFundsNotificationEnabledGlobally: boolean;
    cardInsuranceActivation: boolean;
    cardInsuranceProjectCreation: boolean;
    cardInvalidExpirationDateNotificationEnabledGlobally: boolean;
    cardPermanentlyBlockedNotificationEnabledGlobally: boolean;
    cardPinInvalidNotificationEnabledGlobally: boolean;
    cardSpendingLimitReachedNotificationEnabledGlobally: boolean;
    categoryPurposeOnSCTOutInitiation: boolean;
    changeAccountAdmin: boolean;
    check_order_of_xpay_events: boolean;
    ciao_es_enabled: boolean;
    cms_call_cema_carte_for_choose_pin: true;
    cms_choose_pin_token_always_valid: true;
    create_card_delivery_method_id: boolean;
    create_verification_renewal_cron: boolean;
    createFraudPreventionCampaign: boolean;
    createVerificationRenewalFlowChart: boolean;
    createVerificationRenewalInWaitingForInformationStatus: boolean;
    dashboardAccountClosingLink: true;
    dashboardBanner: null | {
      text: "Please advise your users to be careful with unsolicited calls, texts or emails and to always protect their login and payment info.";
      title: "Ongoing phishing risk";
    };
    dashboardInsightsServiceSection: boolean;
    dashboardNotificationSettings: true;
    dashboardProjectMemberToken: true;
    dataExportAccount: boolean;
    dataExportAccountHolder: boolean;
    dataExportAccountMembership: boolean;
    dataExportCard: boolean;
    dataExportOnboarding: boolean;
    dataExportTransactions: boolean;
    dataExportUser: boolean;
    deferredDebitCard: boolean;
    disable_emails_for_capital_deposit_case: boolean;
    disable_expert_identification_level: true;
    disable_pvid_identification_level: true;
    disable_qes_identification_level: true;
    displaySsoButton: boolean;
    dont_change_default_expiration_for_suvc_one_off_at_update: boolean;
    enable_automatic_identity_documents_upload: boolean;
    enable_card_risk_assessment: boolean;
    enable_credit_zero_amount_author_public_api: boolean;
    enable_document_convertor_from_csv_generation: boolean;
    enable_document_convertor_generation: boolean;
    enable_document_generation_by_document_convertor: boolean;
    enable_mastercard_presettlement: true;
    enable_mastercard_presettlement_reconciliation: true;
    enable_new_account_statement_file_name: boolean;
    enable_transaction_enrichment_from_origin_transaction: boolean;
    enableBouyguesFraudPreventionPage: boolean;
    enableEmailConfirmationAtProjectCreation: boolean;
    enableFraudPreventionPage: boolean;
    enableIdentityTheftPreventionPage: true;
    end_customer_billing_enabled: boolean;
    end_customer_ict_billing_enabled: boolean;
    FeatureFlagCreditEnabled: 1 | 2;
    forceAllowDesktopAuth: boolean;
    free_units_enabled: boolean;
    generate_mastercard_emi_banking: true;
    handle_third_party_events: boolean;
    ict_validation_rejection_enabled: boolean;
    identificationUserInfoCollectionAndReview: boolean;
    identityBirthDataCollection: true;
    incomingForeignTransferScreeningEnabled: true;
    incomingForeignTransferScreeningLimit: 50;
    incomingTransferInstScreeningEnabled: boolean;
    incomingTransferScreeningDualRunEnabled: boolean;
    incomingTransferScreeningEnabled: boolean;
    incomingTransferScreeningLimit: 50;
    initiate_international_credit_transfer_outgoing: boolean;
    initiate_seizures_in_payment: boolean;
    initiate_seizures_in_payment_for_bailiff: boolean;
    inPersonCardPaymentMethodEnabled: boolean;
    isAccountAdminChangeEnabled: boolean;
    isConsentFailedEventEnabled: true;
    isCustomerPasswordResetAvailable: true;
    isDashboardSignupForNewSuspiciousUserCheckEnabled: boolean;
    isForceDesktopAuthenticationEnabled: boolean;
    isPhoneNumberSuspicious: boolean;
    isScaDelegationEnabled: boolean;
    isThreeDsPaymentAllowToBeQueried: boolean;
    kafkaConsumersEnabled: boolean;
    kycAccountHoldersVerificationsView: true;
    la_poste_tracked_international_active: boolean;
    lago_partner_event_use_billing_periods: boolean;
    ledgerSpendingMigrationEnabled: boolean;
    ledgerSpendingMigrationInconsistentAccounts: {
      accounts: Array<
        | "298904e8-9b09-4c51-8b15-0b42e99e8acd"
        | "31a685e6-184b-4483-862b-7fb85c42b190"
        | "517b28e1-35a1-4e4d-8763-c243d2286286"
        | "813e29c3-bc66-4eda-a2b4-8c1c300271cf"
        | "9eece781-14c3-4891-bb00-b3f715f4876b"
        | "fb8baa30-a989-4d30-942f-26749eb24449"
        | "fc4f1e61-31c9-4a5a-87ae-af871854c3c7"
      >;
    };
    ledgerSpendingMigrationLimit: 0 | 1 | 10 | 100 | 1000 | 10000;
    lockRecomputeEnableB2B: true;
    merchantWebBanking: boolean;
    name_matching_use_valid_names_enabled: boolean;
    newGqlGateway: boolean;
    OnboardingV2NoCode: boolean;
    outboundFundsTransferRejectedNotificationEnabledGlobally: boolean;
    outboundFundsTransferSuccessfulNotificationEnabledGlobally: boolean;
    partner_billing_v1_5_enabled: boolean;
    passcodeResetEmailVerification: boolean;
    passcodeResetFaceAuthVerification: boolean;
    passcodeResetIdentificationVerification: boolean;
    passcodeResetNoVerification: boolean;
    pexTcuEventKillSwitch: boolean;
    recurring_suvc_fee_enabled: boolean;
    refundFeesActivateFixOnInvertedAccountIds: boolean;
    reKYCFrontend: boolean;
    reKYCRequestIdentityProof: boolean;
    resolve_iban_mode: "normal" | "passive" | "view";
    return_ict_in_enabled: boolean;
    return_transaction_mutation_ict_in: boolean;
    riskScoringStrategy:
      | "double_run_in_house"
      | "double_run_marble"
      | "double_run_relevant"
      | "in_house_only"
      | "marble_only";
    satd_account_matching_check_for_risk_suspicion: boolean;
    satd_account_matching_mode: "AccountContractAndPayment" | "AccountContractOnly" | "PaymentOnly";
    scaAnonymizeUserInfo: boolean;
    scaIAMDailyMaximumNumberOfSignInPerIp: 10 | 100 | 1000 | 100000 | 20 | 3 | 5;
    scaIAMDailyMaximumNumberOfSignInPerPhoneNumber: 10 | 100 | 1000 | 100000 | 5;
    scaIsCountrySuspiciousCheckEnabled: boolean;
    scaIsInternalOtpEnabled: boolean;
    scaIsLoginChallengeCheckEnabled: boolean;
    scaIsNotificationManagerEnabled: boolean;
    scaIsPhoneCountryCodeBlocked: boolean;
    scaIsWebBankingBrandlessLoginChallengeCheckEnabled: boolean;
    scale_merchant_onboarding_bo: boolean;
    scaleMerchantOnboarding: boolean;
    scaShouldIncludeCustomSubdomainInConsentUrl: boolean;
    scaShouldPassSessionIdToConsentable: boolean;
    scaV1ToV2IdsConversionBatchSize: 0 | 10 | 100 | 20 | 200 | 3 | 5 | 50 | 75;
    scoreThresholdHCaptcha: 0.75 | 0.8 | 0.9 | 1.5;
    scoring_mode: "risk_assessment_first" | "scoring_and_risk_assessment_dry_run" | "scoring_only";
    screeningSctInAndFctInWithNats: boolean;
    sctInstEnabled: boolean;
    send_account_invoice_generated_event: boolean;
    send_activate_physical_card_notification: boolean;
    sendBusinessAndCustomerDataToSardine: boolean;
    sendCreditAndZeroAmountAuthorization: boolean;
    sendValidationInsteadOfForbiddenRejection: boolean;
    sendVerificationRenewalEmails: boolean;
    sepaDirectDebitInV2: true;
    SepaDirectDebitV2ActivationFlag: true;
    setIssuingProcessorCardProductOnRenewFeature: boolean;
    setUpAdminRole: boolean;
    shouldHistorizeIncomingVOPRequest: boolean;
    storeMonextAuthenticationRequest: boolean;
    supportingDocumentsUseBucketV2: boolean;
    swan_generate_missing_bank_details: true;
    swan_supports_local_belgian_iban: boolean;
    swan_supports_local_belgian_iban_dashboard: boolean;
    swan_supports_local_italian_iban_dashboard: true;
    tapToPay: boolean;
    testABTesting: "A" | "B";
    testE: "A" | "B";
    transactionVerification: boolean;
    transfer_suvc_to_legal_rep_on_closed_account_membership: boolean;
    trusted_beneficiary_transfers_consent_free_enabled: boolean;
    twilioRatio: 0 | 0.2 | 0.5 | 0.6 | 0.8 | 0.95 | 1;
    use_account_statement_kms_bucket: boolean;
    use_card_package_on_card_product_creation: boolean;
    use_mailjet_subaccount_for_mass_emailing: true;
    use_notification_manager: boolean;
    useNotificationStackToSendAccountOpenedEmail: boolean;
    useNotificationStackToSendFirstTransferRequestEmail: boolean;
    useNotificationStackToSendNewAccountTcuEmail: boolean;
    useNotificationStackToSendNewMembershipEmail: boolean;
    useNotificationStackToSendSupportingDocumentRequestEmail: boolean;
    useNotificationStackToSendTCUUpdates: boolean;
    usePaymentV2FlowForAccountFunding: boolean;
    useTwilioVerifyServiceSidAlan: true;
    validation_of_postal_code: boolean;
    webhookInitializeExpireOldEventLogsCron: boolean;
    webhookInitializeUpdateConsumerCron: boolean;
    webhookRunExpireOldEventLogsCron: boolean;
    webhookRunUpdateConsumerCron: boolean;
    webhookSendWebhookTokenHeader: boolean;
    webhookSubscriptionLimit: boolean;
  }
}
