query ProjectId {
  projectInfo {
    id
  }
}

fragment OnboardingRedirectInfo on Onboarding {
  id
  account {
    legalRepresentativeMembership {
      id
    }
  }
  statusInfo {
    __typename
    status
  }
  oAuthRedirectParameters {
    state
    redirectUrl
  }
}

query OnboardingRedirect($onboardingId: ID!) {
  onboarding(id: $onboardingId) {
    ...OnboardingRedirectInfo
  }
}

query GetAccountMembershipInvitationData(
  $inviterAccountMembershipId: ID!
  $inviteeAccountMembershipId: ID!
) {
  projectInfo {
    name
    accentColor
    logoUri
  }
  inviterAccountMembership: accountMembership(id: $inviterAccountMembershipId) {
    email
    user {
      firstName
      lastName
    }
    account {
      name
      number
      holder {
        info {
          ... on AccountHolderCompanyInfo {
            name
          }
          ... on AccountHolderIndividualInfo {
            name
          }
        }
      }
    }
  }
  inviteeAccountMembership: accountMembership(id: $inviteeAccountMembershipId) {
    id
    email
    statusInfo {
      __typename
      ... on AccountMembershipInvitationSentStatusInfo {
        restrictedTo {
          firstName
        }
      }
    }
  }
}

mutation FinalizeOnboarding($input: FinalizeOnboardingInput!) {
  finalizeOnboarding(input: $input) {
    __typename
    ... on Rejection {
      message
    }
    ... on FinalizeOnboardingSuccessPayload {
      onboarding {
        ...OnboardingRedirectInfo
      }
    }
  }
}

mutation OnboardIndividualAccountHolder($input: OnboardIndividualAccountHolderInput!) {
  onboardIndividualAccountHolder(input: $input) {
    ... on OnboardIndividualAccountHolderSuccessPayload {
      __typename
      onboarding {
        id
      }
    }
    ... on ForbiddenRejection {
      __typename
      message
    }
    ... on ValidationRejection {
      __typename
      message
    }
  }
}

mutation OnboardCompanyAccountHolder($input: OnboardCompanyAccountHolderInput!) {
  onboardCompanyAccountHolder(input: $input) {
    ... on OnboardCompanyAccountHolderSuccessPayload {
      __typename
      onboarding {
        id
      }
    }
    ... on ForbiddenRejection {
      __typename
      message
    }
    ... on BadRequestRejection {
      __typename
      message
    }
    ... on ValidationRejection {
      __typename
      message
    }
  }
}

mutation BindAccountMembership($input: BindAccountMembershipInput!) {
  bindAccountMembership(input: $input) {
    __typename
    ... on BindAccountMembershipSuccessPayload {
      accountMembership {
        id
      }
    }
    ... on Rejection {
      message
    }
  }
}
