export const env = {
  VERSION: __env.VERSION,
  IS_SWAN_MODE: __env.IS_SWAN_MODE,
  SWAN_ENVIRONMENT: __env.SWAN_ENVIRONMENT,
  GOOGLE_MAP_API_KEY: __env.CLIENT_GOOGLE_MAPS_API_KEY,
  PLACEKIT_API_KEY: __env.CLIENT_PLACEKIT_API_KEY,
  BANKING_URL: __env.BANKING_URL,
  PAPPERS_API_URL: "",
};
