fragment Address on AddressInfo {
  addressLine1
  addressLine2
  city
  country
  postalCode
  state
}

fragment BirthInfo on BirthInfo {
  city
  country
  postalCode
  birthDate
}

fragment IndividualRepresentative on OnboardingIndividualRepresentative {
  firstName
  lastName
  roles
  nationality
  email
  birthInfo {
    ...BirthInfo
  }
  address {
    ...Address
  }
}

fragment OnboardingStatus on OnboardingStatusInfo {
  __typename
  status
  validationVersion
  ... on OnboardingInvalidStatusInfo {
    errors {
      field
      errors
    }
  }
}

fragment SupportingDocument on SupportingDocument {
  id
  supportingDocumentPurpose
  supportingDocumentType
  updatedAt
  statusInfo {
    __typename
    status
    ... on SupportingDocumentUploadedStatusInfo {
      filename
    }
    ... on SupportingDocumentValidatedStatusInfo {
      filename
    }
    ... on SupportingDocumentRefusedStatusInfo {
      reasonCode
      reason
      filename
    }
  }
}

fragment SupportingDocumentCollection on SupportingDocumentCollection {
  id
  requiredSupportingDocumentPurposes {
    name
  }
  statusInfo {
    status
  }
  supportingDocuments {
    ...SupportingDocument
  }
}
fragment CompanyInfo on CompanyInfo {
  registrationNumber
  name
  tradeName
  registrationDate
  legalFormCode
  vatNumber
  taxIdentificationNumber
  businessActivityDescription
  businessActivityCode
  address {
    ...Address
  }
  headcount
  forecastYearlyIncome
  monthlyPaymentVolume
  regulatoryClassification
  websites
  companyType
  ultimateBeneficialOwners {
    firstName
    lastName
    qualificationType
    controlTypes
    ownership {
      totalPercentage
      type
    }
  }
  representatives {
    ... on OnboardingCompanyRepresentative {
      entityName
      registrationNumber
      roles
    }
    ... on OnboardingIndividualRepresentative {
      ...IndividualRepresentative
    }
  }
}

fragment IndividualOrCompanyOnboarding on AccountHolderOnboardingBase {
  id
  oAuthRedirectParameters {
    redirectUrl
  }
  statusInfo {
    ...OnboardingStatus
  }
  supportingDocumentCollection {
    ...SupportingDocumentCollection
  }
  projectInfo {
    id
    name
    accentColor
    logoUri
  }
}

fragment CompanyOnboarding on CompanyAccountHolderOnboarding {
  ...IndividualOrCompanyOnboarding
  accountInfo {
    name
    country
  }
  accountAdmin {
    birthInfo {
      ...BirthInfo
    }
    email
    firstName
    preferredLanguage
    lastName
    nationality
    address {
      ...Address
    }
    taxIdentificationNumber
    typeOfRepresentation
  }
  company {
    ...CompanyInfo
  }
}

fragment IndividualOnboarding on IndividualAccountHolderOnboarding {
  ...IndividualOrCompanyOnboarding
  accountInfo {
    name
    country
  }
  accountAdmin {
    birthInfo {
      ...BirthInfo
    }
    email
    employmentStatus
    firstName
    preferredLanguage
    lastName
    monthlyIncome
    nationality
    address {
      ...Address
    }
    sourcesOfFunds
    unitedStatesTaxInfo {
      isUnitedStatesPerson
      unitedStatesTaxIdentificationNumber
    }
    taxIdentificationNumber
  }
}

query GetPublicOnboarding($id: ID!) {
  publicAccountHolderOnboarding(id: $id) {
    __typename
    ... on PublicAccountHolderOnboardingSuccessPayload {
      onboarding {
        ...CompanyOnboarding
        ...IndividualOnboarding
      }
    }
  }
}

query GetPublicCompamyInfoRegistryData($input: PublicCompanyInfoRegistryDataInput!) {
  publicCompanyInfoRegistryData(input: $input) {
    ... on PublicCompanyInfoRegistryDataSuccessPayload {
      companyInfo {
        ...CompanyInfo
      }
    }
    ... on Rejection {
      message
    }
  }
}

query GetPublicOnboardingVersion($id: ID!) {
  publicAccountHolderOnboarding(id: $id) {
    ... on PublicAccountHolderOnboardingSuccessPayload {
      onboarding {
        ... on CompanyAccountHolderOnboarding {
          id
          statusInfo {
            validationVersion
          }
        }
        ... on IndividualAccountHolderOnboarding {
          id
          statusInfo {
            validationVersion
          }
        }
      }
    }
  }
}

query GetLegalForms($country: CCA3!) {
  legalForms(country: $country) {
    country
    localName
    code
  }
}

fragment UpdateValidationErrors on ValidationRejection {
  __typename
  fields {
    path
    code
    message
  }
}

mutation UpdatePublicIndividualAccountHolderOnboarding(
  $input: UpdatePublicIndividualAccountHolderOnboardingInput!
) {
  updatePublicIndividualAccountHolderOnboarding(input: $input) {
    ... on UpdatePublicIndividualAccountHolderOnboardingSuccessPayload {
      onboarding {
        ...IndividualOnboarding
      }
    }
    ... on ValidationRejection {
      ...UpdateValidationErrors
    }
  }
}

mutation UpdatePublicCompanyAccountHolderOnboarding(
  $input: UpdatePublicCompanyAccountHolderOnboardingInput!
) {
  updatePublicCompanyAccountHolderOnboarding(input: $input) {
    ... on UpdatePublicCompanyAccountHolderOnboardingSuccessPayload {
      onboarding {
        ...CompanyOnboarding
      }
    }
    ... on ValidationRejection {
      ...UpdateValidationErrors
    }
  }
}

mutation GenerateSupportingDocumentUploadUrl($input: GenerateSupportingDocumentUploadUrlInput!) {
  generateSupportingDocumentUploadUrl(input: $input) {
    __typename
    ... on GenerateSupportingDocumentUploadUrlSuccessPayload {
      supportingDocumentId
      upload {
        fields {
          key
          value
        }
        url
      }
    }
  }
}

mutation DeleteSupportingDocument($input: DeleteSupportingDocumentInput!) {
  deleteSupportingDocument(input: $input) {
    __typename
    ... on DeleteSupportingDocumentSuccessPayload {
      id
    }
    ... on Rejection {
      message
    }
  }
}

fragment AccountAdminChangeInfo on AccountAdminChange {
  id
  reason
  isNewAdminLegalRepresentative
  isRequesterNewAdmin
  accountHolder {
    accounts {
      name
    }
    name
    projectInfo {
      accentColor
      logoUri
      name
    }
  }
  admin {
    firstName
    lastName
    email
    phoneNumber
    birthCountry
    birthDate
  }
  requester {
    firstName
    lastName
    email
    phoneNumber
  }
  supportingDocumentCollection {
    id
    statusInfo {
      status
    }
    requiredSupportingDocumentPurposes {
      name
    }
    supportingDocuments {
      ...SupportingDocument
    }
  }
}

query AccountAdminChange($accountAdminChangeId: ID!) {
  publicAccountAdminChange(accountAdminChangeId: $accountAdminChangeId) {
    ... on AccountAdminChange {
      ...AccountAdminChangeInfo
    }
  }
}

mutation UpdateAccountAdminChange($input: PublicUpdateAccountAdminChangeInput!) {
  publicUpdateAccountAdminChange(input: $input) {
    __typename
    ... on PublicUpdateAccountAdminChangeSuccessPayload {
      accountAdminChange {
        ...AccountAdminChangeInfo
      }
    }
    ... on Rejection {
      message
    }
  }
}

mutation FinalizeAccountAdminChange($accountAdminChangeId: ID!) {
  publicFinalizeAccountAdminChange(accountAdminChangeId: $accountAdminChangeId) {
    ... on PublicFinalizeAccountAdminChangeSuccessPayload {
      success
    }
  }
}
