name: Test & build

on:
  push:
    branches:
      - "*"

jobs:
  test-and-build:
    name: Test & build
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read # This is required for actions/checkout
      id-token: write # This is required for requesting the JWT
      packages: read # This is required for npm.pkg.github.com
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: lts/*
          cache: pnpm
          registry-url: https://npm.pkg.github.com

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}

      # - name: Check licenses
      #   run: pnpm license-check

      # - name: GraphQL Codegen
      #   run: pnpm graphql-codegen

      # - name: Typecheck
      #   run: pnpm typecheck

      # - name: Lint
      #   run: pnpm lint

      # - name: Run tests
      #   run: pnpm test

      # - name: Compile project
      #   env:
      #     NODE_OPTIONS: "--max_old_space_size=4096"
      #   run: pnpm build

      # # Overwrite package.json version with the commit SHA
      # # This allows to identify the exact code deployed in master
      # - name: Overwrite package.json version
      #   if: ${{ github.repository == 'swan-io/swan-partner-frontend' && contains('refs/heads/main', github.ref) }}
      #   run: jq --arg v ${GITHUB_SHA:0:7} '.version = $v' server/package.json > package.json.tmp && mv package.json.tmp server/package.json

      # - name: Inject & upload source maps to Grafana Faro
      #   if: ${{ github.repository == 'swan-io/swan-partner-frontend' && contains('refs/heads/main', github.ref) }}
      #   run: |
      #     scripts/sourcemaps/uploadSourcemaps.sh banking ${GITHUB_SHA:0:7} ${{ secrets.FARO_APP_ID_BANKING }}
      #     scripts/sourcemaps/uploadSourcemaps.sh onboarding ${GITHUB_SHA:0:7} ${{ secrets.FARO_APP_ID_ONBOARDING }}
      #     scripts/sourcemaps/uploadSourcemaps.sh payment ${GITHUB_SHA:0:7} ${{ secrets.FARO_APP_ID_PAYMENT }}
      #   env:
      #     FARO_SOURCEMAP_ENDPOINT: https://faro-api-prod-eu-west-6.grafana.net/faro/api/v1
      #     FARO_API_KEY: ${{ secrets.FARO_API_KEY }}
      #     FARO_STACK_ID: ${{ secrets.FARO_STACK_ID }}

      # - name: Push onboarding translation keys
      #   if: ${{ github.repository == 'swan-io/swan-partner-frontend' && contains('refs/heads/main', github.ref) }}
      #   run: pnpm localazy upload onboarding -r ${{ secrets.LOCALAZY_ONBOARDING_READ_KEY }} -w ${{ secrets.LOCALAZY_ONBOARDING_WRITE_KEY }}

      # - name: Push banking translation keys
      #   if: ${{ github.repository == 'swan-io/swan-partner-frontend' && contains('refs/heads/main', github.ref)}}
      #   run: pnpm localazy upload banking -r ${{ secrets.LOCALAZY_BANKING_READ_KEY }} -w ${{ secrets.LOCALAZY_BANKING_WRITE_KEY }}

      # - name: Push payment translation keys
      #   if: ${{ github.repository == 'swan-io/swan-partner-frontend' && contains('refs/heads/main', github.ref)}}
      #   run: pnpm localazy upload payment -r ${{ secrets.LOCALAZY_PAYMENT_READ_KEY }} -w ${{ secrets.LOCALAZY_PAYMENT_WRITE_KEY }}

      # - name: Configure AWS Credentials
      #   if: ${{ github.repository == 'swan-io/swan-partner-frontend' && contains('refs/heads/main', github.ref) || contains(github.event.head_commit.message, '[dockerize]')}}
      #   uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
      #   with:
      #     role-to-assume: ${{ secrets.AWS_ROLE }}
      #     aws-region: eu-west-1

      # - name: Login to Docker Registry
      #   if: ${{ github.repository == 'swan-io/swan-partner-frontend' && contains('refs/heads/main', github.ref) || contains(github.event.head_commit.message, '[dockerize]') }}
      #   uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
      #   with:
      #     registry: ${{ secrets.DOCKER_REGISTRY }}

      # - name: Dockerize & Push to Registry
      #   if: ${{ github.repository == 'swan-io/swan-partner-frontend' && contains('refs/heads/main', github.ref) || contains(github.event.head_commit.message, '[dockerize]') }}
      #   uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5.4.0
      #   with:
      #     context: .
      #     file: Dockerfile-swan
      #     push: true
      #     tags: |
      #       ${{ secrets.DOCKER_REGISTRY }}/swan-partner-frontend:master-${{ github.sha }}
      #       ${{ secrets.DOCKER_REGISTRY }}/swan-partner-frontend:master-${{ github.ref_name }}

      - name: Deploy
        # if: ${{ github.repository == 'swan-io/swan-partner-frontend' && contains('refs/heads/main', github.ref) }}
        run: pnpm deploy-ci
        env:
          TAG: master-${{ github.sha }}
          DEPLOY_SWAN_APP_ID: ${{ secrets.DEPLOY_SWAN_APP_ID }}
          DEPLOY_SWAN_APP_SECRET: ${{ secrets.DEPLOY_SWAN_APP_SECRET }}
          DEPLOY_ENVIRONMENT: master
          DEPLOY_APP_NAME: partner-frontend
