name: Build docs

on:
  push:
    branches:
      - "main"

jobs:
  docs:
    name: Build docs
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install & build
        run: cd docs && pnpm install --frozen-lockfile && pnpm build

      - name: Deploy
        if: "contains('refs/heads/main', github.ref)"
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
