name: E2E tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: E2E tests
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Add hosts to /etc/hosts
        run: |
          sudo echo "127.0.0.1 banking.swan.local" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 onboarding.swan.local" | sudo tee -a /etc/hosts

      - uses: SpicyPizza/create-envfile@v2.0
        with:
          fail_on_empty: true
          file_name: .env.e2e
          envkey_NODE_ENV: "test"
          envkey_LOG_LEVEL: "error"
          envkey_PARTNER_ADMIN_API_URL: ${{ secrets.E2E_PARTNER_ADMIN_API_URL }}
          envkey_PARTNER_API_URL: ${{ secrets.E2E_PARTNER_API_URL }}
          envkey_UNAUTHENTICATED_API_URL: ${{ secrets.E2E_UNAUTHENTICATED_API_URL }}
          envkey_OAUTH_SERVER_URL: ${{ secrets.E2E_OAUTH_SERVER_URL }}
          envkey_OAUTH_CLIENT_ID: ${{ secrets.E2E_OAUTH_CLIENT_ID }}
          envkey_OAUTH_CLIENT_SECRET: ${{ secrets.E2E_OAUTH_CLIENT_SECRET }}
          envkey_COOKIE_KEY: ${{ secrets.E2E_COOKIE_KEY }}
          envkey_BANKING_URL: "http://banking.swan.local:8080"
          envkey_ONBOARDING_URL: "http://onboarding.swan.local:8080"
          envkey_CLIENT_GOOGLE_MAPS_API_KEY: ${{ secrets.E2E_GOOGLE_MAPS_API_KEY }}
          envkey_TEST_KEY: ${{ secrets.E2E_TEST_KEY }}
          envkey_PHONE_NUMBER: ${{ secrets.E2E_PHONE_NUMBER }}
          envkey_PASSCODE: ${{ secrets.E2E_PASSCODE }}
          envkey_SANDBOX_USER_BENADY_ID: ${{ secrets.E2E_SANDBOX_USER_BENADY_ID }}
          envkey_SANDBOX_USER_SAISON_ID: ${{ secrets.E2E_SANDBOX_USER_SAISON_ID }}
          envkey_TWILIO_ACCOUNT_ID: ${{ secrets.E2E_TWILIO_ACCOUNT_ID }}
          envkey_TWILIO_AUTH_TOKEN: ${{ secrets.E2E_TWILIO_AUTH_TOKEN }}
          envkey_WEBHOOK_SITE_API_KEY: ${{ secrets.E2E_WEBHOOK_SITE_API_KEY }}

      - name: Install dependencies
        run: yarn install --pure-lockfile

      - name: GraphQL Codegen
        run: yarn graphql-codegen

      - name: Install chromium
        run: yarn playwright install-deps chromium

      - name: Run E2E tests
        run: CI=true yarn test-e2e

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: playwright-report
          path: tests/results
          retention-days: 30
