name: E2E tests (release)

on:
  pull_request:
    types: [closed]

concurrency:
  group: end-to-end
  cancel-in-progress: false

jobs:
  test:
    name: E2E tests (release)
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 60
    permissions:
      packages: read # This is required for npm.pkg.github.com
    if: ${{ github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release-v') }}
    env:
      REF_BRANCH: ${{ github.event.pull_request.head.ref }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: lts/*
          cache: pnpm
          registry-url: https://npm.pkg.github.com

      - name: Edit /etc/hosts
        run: |
          sudo echo "127.0.0.1 banking.swan.localhost" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 onboarding.swan.localhost" | sudo tee -a /etc/hosts

      - name: Write .env.e2e file
        run: |
          echo "NODE_ENV=test" > .env.e2e
          echo "LOG_LEVEL=error" >> .env.e2e
          echo "PARTNER_ADMIN_API_URL=${{ secrets.E2E_PARTNER_ADMIN_API_URL }}" >> .env.e2e
          echo "PARTNER_API_URL=${{ secrets.E2E_PARTNER_API_URL }}" >> .env.e2e
          echo "UNAUTHENTICATED_API_URL=${{ secrets.E2E_UNAUTHENTICATED_API_URL }}" >> .env.e2e
          echo "OAUTH_SERVER_URL=${{ secrets.E2E_OAUTH_SERVER_URL }}" >> .env.e2e
          echo "OAUTH_CLIENT_ID=${{ secrets.E2E_OAUTH_CLIENT_ID }}" >> .env.e2e
          echo "OAUTH_CLIENT_SECRET=${{ secrets.E2E_OAUTH_CLIENT_SECRET }}" >> .env.e2e
          echo "COOKIE_KEY=${{ secrets.E2E_COOKIE_KEY }}" >> .env.e2e
          echo "BANKING_URL=http://banking.swan.localhost:8080" >> .env.e2e
          echo "ONBOARDING_URL=http://onboarding.swan.localhost:8080" >> .env.e2e
          echo "PAYMENT_URL=http://payment.swan.localhost:8080" >> .env.e2e
          echo "IDENTITY_URL=http://identity.swan.localhost:8080" >> .env.e2e
          echo "TEST_KEY=${{ secrets.E2E_TEST_KEY }}" >> .env.e2e
          echo "PHONE_NUMBER=${{ secrets.E2E_PHONE_NUMBER }}" >> .env.e2e
          echo "PASSCODE=${{ secrets.E2E_PASSCODE }}" >> .env.e2e
          echo "TWILIO_ACCOUNT_ID=${{ secrets.E2E_TWILIO_ACCOUNT_ID }}" >> .env.e2e
          echo "TWILIO_AUTH_TOKEN=${{ secrets.E2E_TWILIO_AUTH_TOKEN }}" >> .env.e2e
          echo "WEBHOOK_SITE_API_KEY=${{ secrets.E2E_WEBHOOK_SITE_API_KEY }}" >> .env.e2e

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}

      - name: Get playwright version
        run: |
          PLAYWRIGHT_VERSION=$(npm ls @playwright/test | grep @playwright | sed 's/.*@//')
          echo "Playwright version: $PLAYWRIGHT_VERSION"
          echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV

      - name: Cache playwright
        id: cache-playwright
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ env.PLAYWRIGHT_VERSION }}

      - name: Setup playwright
        if: ${{ steps.cache-playwright.outputs.cache-hit != 'true' }}
        run: pnpm playwright install --with-deps

      - name: GraphQL Codegen
        run: pnpm graphql-codegen

      - name: Run E2E tests
        run: pnpm test-e2e
        env:
          CI: true

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: ${{ failure() }}
        with:
          name: tests-results
          path: tests/results/
          retention-days: 7

      - name: Get version
        id: version
        run: echo version="$REF_BRANCH" | sed -e 's/release-//g' >> $GITHUB_OUTPUT

      - name: Notify Slack about success
        if: ${{ success() }}
        uses: slackapi/slack-github-action@fcfb566f8b0aab22203f066d80ca1d7e4b5d05b3 # v1.27.1
        with:
          channel-id: "C04HS607GMD"
          payload: |
            {
              "unfurl_links": false,
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "✨ End to End tests succeeded for pre-release ${{ steps.version.outputs.version }}"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "Open on GitHub",
                      "emoji": true
                    },
                    "value": "github",
                    "url": "https://github.com/swan-io/swan-partner-frontend/actions/runs/${{ github.run_id }}",
                    "action_id": "button-action"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.E2E_SLACK_BOT_TOKEN }}

      - name: Notify Slack about failure
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@fcfb566f8b0aab22203f066d80ca1d7e4b5d05b3 # v1.27.1
        with:
          channel-id: "C04HS607GMD"
          payload: |
            {
              "unfurl_links": false,
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "💥 End to End tests failed for pre-release ${{ steps.version.outputs.version }}"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "Open on GitHub",
                      "emoji": true
                    },
                    "value": "github",
                    "url": "https://github.com/swan-io/swan-partner-frontend/actions/runs/${{ github.run_id }}",
                    "action_id": "button-action"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.E2E_SLACK_BOT_TOKEN }}
