name: Release

on:
  release:
    types: [released]

jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read # This is required for actions/checkout
      id-token: write # This is required for requesting the JWT
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: lts/*
          cache: pnpm

      - name: Deploy prod
        if: ${{ github.repository == 'swan-io/swan-partner-frontend' }}
        run: pnpm deploy-ci
        env:
          TAG: prod-${{ github.ref_name }}
          DEPLOY_SWAN_APP_ID: ${{ secrets.DEPLOY_SWAN_APP_ID }}
          DEPLOY_SWAN_APP_SECRET: ${{ secrets.DEPLOY_SWAN_APP_SECRET }}
          DEPLOY_ENVIRONMENT: prod
          DEPLOY_APP_NAME: partner-frontend
